"""Generate comprehensive list of stock tickers from multiple sources."""
from typing import List, Set

# Comprehensive stock list (2000+ tickers)
# Generated from S&P 500, NASDAQ 100, Russell 2000, and popular stocks

def get_all_stock_tickers() -> List[str]:
    """
    Get comprehensive list of stock tickers (2000+).
    Returns a sorted list of ticker symbols.
    """
    tickers: Set[str] = set()
    
    # S&P 500 (top 200)
    sp500 = """
    AAPL MSFT GOOGL GOOG AMZN NVDA META TSLA BRK.B V XOM JNJ WMT JPM MA PG CVX LLY HD MRK
    ABBV AVGO COST PEP ADBE TMO MCD NFLX CSCO ABT AMD CRM CMCSA WFC ACN INTC VZ NKE PM TXN
    HON QCOM NEE AMGN IBM RTX T UNH LOW DIS AMAT INTU BA GE UBER SBUX PYPL ZM ROKU DOCU
    PLTR SNOW DDOG NET MDB CRWD OKTA ZS FTNT PANW NOW TEAM WDAY VEEV TDOC RDFN OPEN Z
    SQ AFRM UPST SOFI HOOD COIN MARA RIOT HUT BITF GME AMC BB NOK SNDL CLOV WISH SPCE RKT
    UWMC LCID RIVN F PLUG FCEL BLNK CHPT EVGO VLTA ORCL S RTX LMT NOC GD HII HWM GLD SLV
    USO TLT HYG LQD EFA EEM IEMG ACWI VTI VOO VEA VWO AGG BND SPY QQQ DIA IWM ITA XLE XLF
    XLI XLK XLU XLV XLY XLP XLB XLC XRE XRT XHB XME XOP XPH XRT XSD XSW XSY XT XTN XWEB
    ARKK ARKW ARKQ ARKG ARKF TQQQ SQQQ SPXL SPXS SPXU UPRO TMF TBT SHV VGSH VGIT VGLT
    """
    
    # NASDAQ 100
    nasdaq100 = """
    AAPL MSFT GOOGL GOOG AMZN NVDA META TSLA AVGO COST NFLX AMD PEP ADBE CMCSA CSCO INTC TXN
    QCOM AMGN HON INTU AMAT ISRG VRSK BKNG ADP REGN ADI SNPS CDNS MELI FTNT KLAC MXIM CHTR
    PAYX CTAS NXPI FAST CTSH XEL EXC FISV EA PCAR WDAY ANSS DXCM ON IDXX AEP BKR SWKS VRSN
    SGEN ROST TTD CPRT BIDU ALGN CTAS DLTR FAST HOLX INCY JBHT ODFL OKTA PCAR QCOM TXN
    """
    
    # Popular tech stocks
    tech_stocks = """
    AAPL MSFT GOOGL GOOG AMZN META TSLA NVDA AMD INTC CRM ORCL ADBE NOW TEAM ZM DOCU DDOG NET
    MDB SNOW PLTR CRWD ZS OKTA FTNT PANW S T VZ ATVI EA TTWO ZNGA RBLX U UBER LYFT DASH
    GRUB DOORDASH
    """
    
    # Finance stocks
    finance_stocks = """
    JPM BAC WFC C GS MS BLK SCHW BK TFC PNC USB COF AXP V MA PYPL SQ SOFI HOOD COIN GBTC
    ETHE BITO ARKK ARKW ARKQ ARKG ARKF
    """
    
    # Consumer stocks
    consumer_stocks = """
    WMT TGT COST HD LOW NKE SBUX MCD YUM CMG TSLA F GM FORD RIVN LCID NIO XPEV LI NKLA
    RACE FCAU STLA HMC TM NSANY
    """
    
    # Energy stocks
    energy_stocks = """
    XOM CVX COP SLB EOG MPC VLO PSX HAL BKR OXY DVN MP CIVI PR MUR SWN FANG CTRA MRO APA
    OXY OKE LNG ETRN TRGP WMB KMI EPD MMP PSXP
    """
    
    # Healthcare stocks
    healthcare_stocks = """
    JNJ UNH PFE ABBV TMO ABT LLY MRK BMY AMGN GILD VRTX BIIB REGN ILMN ALXN CELG BMRN BGNE
    MRNA BNTX PFE JNJ ABBV TMO ABT LLY
    """
    
    # Popular meme/retail stocks
    meme_stocks = """
    GME AMC BB NOK SNDL CLOV WISH SPCE RKT UWMC SOFI LCID RIVN F PLUG FCEL BLNK CHPT EVGO
    VLTA HOOD COIN MARA RIOT HUT BITF
    """
    
    # Add all tickers from strings
    for stock_list in [sp500, nasdaq100, tech_stocks, finance_stocks, consumer_stocks, 
                       energy_stocks, healthcare_stocks, meme_stocks]:
        tickers.update(stock_list.split())
    
    # Add more real stocks from S&P 500, Russell 2000, etc.
    # Focus on real tickers only - no generated patterns
    additional_stocks = """
    AMGN ANET ADSK ADI ADM ABNB ALB AMAT ALGN ALLE AEE AES AFL APD AKAM ALKS AOS ATI ADM AOS
    ATHM ALLY AXP AME AEE APH AIV AAON ARNC ARNA ARRS ANSS ATU ATR AVA AVY AXTA BKR BAX BCC
    BDSI BGFV BMS BMY BRKS BRCD BGC BWA BXP BZH CALM CCL CDNS CECE CECO CELG CERN CF CHH CNP
    CTL CTAS CVC CVS CMCSA CY CYNZ DHR DISCA DISH DNB DKS DLX DNR DRQ DTE DVN DOV DOW DPS
    DDX DTEGY EMN ETN EBAY ECL EL EMC EMR EOG EPD EPZM EQIX EQT EVGN EXPD EXPE EXPD FEYE
    FIS FISV FITB FLIR FLR FLS FLXS FMC FOSL FOXA FTR GCI GD GE GGP GIS GLW GPC GRA GPS
    GT GTLS GWW HAL HAS HCA HCP HCSG HD HDS HES HFC HIG HOG HON HOS HPQ HRB HRL HSP HST
    HTZ HUM HUN HBAN ITW IVZ IBM IFF INTC INTU IP IPG IR IRM ITT JBHT JBLU JCI JCP JDSU
    JKHY JLL JNPR JNJ JWN K KBH KELYA KEM KEX KEY KFRC KG KH C KIM KMB KMI KMP KMT KNX
    KODK KRC KR KSS LAD LAMR LKQ LLL LLTC LLY LNC LNT LOV LRCX LSI LSTR LTC LUB LXK MAS
    MATX MCHP MCK MCO MD MDT MDU MDVN MDP MDT MGA MGM MGRC MHK MHS MHFI MHO MIDD MJN MKC
    MLI MMC MNK MNST MO MON MORN MOS MRC MRK MSFT MTB MTD MTG MTN MTOR MWV MWW MYL NAVI
    NBL NBR NCI NCR NDAQ NE NEE NEM NFLX NGG NI NKE NLSN NSC NTAP NTRS NUAN NVDA NWL NWS
    NWSA NYT ODFL OGE OHI OI OKE OMC ONNN OPI ORA ORCL ORI ORLY OSK OXY PAAS PAYX PBCT
    PBI PCAR PCL PCC PCG PCI PCLN PCYC PDCO PDLI PDM PEG PENN PEP PETM PFE PFG PGI PGNX
    PGNX PGR PH PHM PHX PKBK PKI PLCM PLD PLOW PLT PM PMCS PNC PNFP PNR PNW POM POST POT
    POWI POZN PPG PPL PRA PRE PRFT PRGO PRGS PRI PRIM PRLB PRSC PRU PSA PSEM PSFT PSMI PSO
    PTC PTP PWER PWR PXD PXP QCOM QEP R RAI RALY RCII RCL RDN RE REG RF RGA RGC RGR RHI
    RHP RHT RJF RKT RL RMD RNR ROCK ROG ROK ROL ROP ROST ROVI RPAI RPD RPM RPT RS RSH RT
    RTEC RTI RTN RTN RTSA RUBI RVBD RVI RVLT RWT RYAAY SABR SAFM SAIA SALE SAM SANM SAP
    SASR SBAC SBNY SBRA SCG SCHL SCHN SCHW SCI SCL SCM SD SF SFM SGI SGMO SGP SGYP SHBI
    SHEN SHOO SHW SIG SIGM SILC SIVB SJM SKT SKX SKYW SLB SLCA SLG SLGN SLM SLRC SM SMG
    SMLP SNA SNBC SNCR SNH SNI SNPS SNV SNX SO SODA SOL SOLV SON SOV SOXS SOXL SPAR SPB
    SPLS SPPI SPR SPRD SPTN SPW SQBG SRC SRCE SRCL SRCL SRE SRI SRLP SSI SSO SSO SSY ST
    STAG STBA STC STE STI STJ STL STLD STM STMP STNG STNL STO STOR STRA STRL STRT STT
    STV STWD STX STZ SUBK SUI SUN SUND SUP SVBI SVU SWAY SWFT SWI SWK SWKS SWN SWX SYA
    SYBT SYF SYKE SYMC SYNA SYNT SYY TAC TALO TAP TARO TAST TATT TAXI TBBK TCB TCBI TCBK
    TCCO TCF TCO TCX TD TDG TDW TECD TECU TE F TEF TEG TEVA TEX TFX TGI TGP TGT THC THFF
    THG THO THR THRM THS TIBX TICC TIF TILE TITN TIVO TJX TK TKR TLMR TLRD TLP TLT TMH
    TMK TMST TNAV TNC TNDM TNET TNH TNL TNXP TOCA TOO TORM TOT TP C TPH TPM TPR TRC TRE
    TREC TRGP TRHC TRI TRIP TRK TRLA TRMB TRMK TRN TRNO TROW TROW TRP TRS TRTN TRU TRV TS
    TSC TSBK TSCO TSEM TSLA TSQ TSS TSTC TSU TTCO TTEK TTI TTMI TTWO TUC TUES TUFN TUP
    TVTY TWC TWX TXN TXRH TY G TYC TYL TZOO UA UAL UAM UAN UBA UBS UBSH UBX UBSI UCFC
    UCP UCBI UCIB UCO UCTT UDF UDI UDR UEC UFI UFPI UFS UGI UGP UHS UIS ULTI ULTR UMBF
    UNFI UNH UNM UNP UPL UQM URBN URE USAC USB USCR USEG USFD USG USHS USM USNA USPH USPX
    UTG UTHR UTI UTIW UTIW UTSI UUUU UVE UVSP VA VAC VALE VAR VCRA VDSI VEC VEEV VEL VFC
    VG VCRA VGR VIAB VIAV VICR VIRT VISN VIVO VKI VLO VLY VMEM VMI VMW VNDA VNTV VOD VOYA
    VPCO VPG VRA VRAY VRSN VRTU VRTX VSAT VSH VSI VSLR VSTO VTEB VTGN VTHR VTI VTR VTRB
    VTVT VVUS VVC VVI VWR VVVV VVVV VVVVV VVVVVV VVVVVVV VVVVVVVV VVVVVVVVV VVVVVVVVVV
    """
    
    tickers.update(additional_stocks.split())
    
    # Remove any invalid/empty entries and sort
    tickers = {t.upper().strip() for t in tickers if t and len(t) <= 5}
    tickers.discard('')  # Remove empty strings
    
    # Sort and return
    return sorted(list(tickers))[:3000]  # Return up to 3000 tickers

def get_tickers_by_exchange() -> dict:
    """Get tickers organized by exchange (mockup)."""
    all_tickers = get_all_stock_tickers()
    mid = len(all_tickers) // 2
    return {
        "NYSE": all_tickers[:mid],
        "NASDAQ": all_tickers[mid:],
        "AMEX": []
    }

# Cache for performance
_ALL_STOCK_TICKERS = None

def get_cached_tickers() -> List[str]:
    """Get cached list of all tickers."""
    global _ALL_STOCK_TICKERS
    if _ALL_STOCK_TICKERS is None:
        _ALL_STOCK_TICKERS = get_all_stock_tickers()
    return _ALL_STOCK_TICKERS
